# -*- coding: utf-8 -*-
"""TA-2_Assignment_NLP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JR-JUMpxjSgA4w_eONRWFrEtT49vriar
"""

!pip install easyocr opencv-python matplotlib

!pip install indic-nlp-library
!git clone https://github.com/anoopkunchukuttan/indic_nlp_resources.git
import os
os.environ["INDIC_RESOURCES_PATH"] = "./indic_nlp_resources"

!pip install stanza

import stanza

# Download Hindi models (run only once)
stanza.download('hi')

import easyocr
import cv2
import matplotlib.pyplot as plt
from indicnlp.tokenize import indic_tokenize
import stanza

# Load image (no preprocessing)
image_path = '/content/my_handwritten.jpeg'
image = cv2.imread(image_path)

# Show original image
plt.imshow(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))
plt.title("🖼️ Original Image")
plt.axis("off")
plt.show()

# OCR using EasyOCR with Hindi language support
reader = easyocr.Reader(['hi'])
results = reader.readtext(image, decoder='beamsearch')  # Beamsearch improves accuracy

# Extract text
print("\n📝 Detected Text:\n")
extracted_text = ""
for bbox, text, conf in results:
    print(f"{text} (Confidence: {conf:.2f})")
    extracted_text += text + " "

# Tokenize using Indic NLP
print("\n🔠 Tokenized Text:")
tokens = list(indic_tokenize.trivial_tokenize(extracted_text.strip(), lang='hi'))
print(tokens)

# POS Tagging using Stanza
print("\n🏷️ POS Tags:")
stanza.download('hi')
nlp = stanza.Pipeline(lang='hi', processors='tokenize,pos')
doc = nlp(extracted_text)
for sentence in doc.sentences:
    for word in sentence.words:
        print(f"{word.text}\t-> {word.upos}")